### ISSUE TITLE
Another ROR2 patch created another error.

### ISSUE THREAD

**Issue by VTrista** [Phedg1Studios/StartingItemsGUI#7]
Since Risk of Rain 2 now updated to 1.1.1.2, a new softlock arrived, that is different from the old one from the initial anniversary update. Two errors appear here. One before the game even loads (it of course still loads but maybe it has a meaning) and one upon trying to open the Starting Items GUI menu.

Error 1: [Error  : Unity Log] Script error (StartingItemsGUI): OnEnable() can not take parameters.

Error 2: [Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <2fa7a6a452ca43df998f07fd1486c0df>:IL_001E)
Phedg1Studios.StartingItemsGUI.UIDrawer.GetStoreItems () (at <2865d837151c42fab41c412845690f61>:IL_001B)
Phedg1Studios.StartingItemsGUI.UIDrawer.DrawShop () (at <2865d837151c42fab41c412845690f61>:IL_0000)
Phedg1Studios.StartingItemsGUI.UIDrawer.DrawUI () (at <2865d837151c42fab41c412845690f61>:IL_001E)
Phedg1Studios.StartingItemsGUI.UIDrawer.OpenStartingItems () (at <2865d837151c42fab41c412845690f61>:IL_0010)
UnityEngine.Events.InvokableCall.Invoke () (at <2cc17dca390941eeb4d7b2ff1f84696a>:IL_0011)
UnityEngine.Events.UnityEvent.Invoke () (at <2cc17dca390941eeb4d7b2ff1f84696a>:IL_0023)
RoR2.UI.MainMenu.BaseMainMenuScreen.OnEnter (RoR2.UI.MainMenu.MainMenuController mainMenuController) (at <6e882c67227c45d48048fa96336d8982>:IL_0007)
RoR2.UI.MainMenu.MainMenuController.Update () (at <6e882c67227c45d48048fa96336d8982>:IL_00B1)

How to replicate:
Have Risk of Rain 2 on version 1.1.1.2
Fix the first softlock by editing the code of the StartingItemsGUI mod
Start the game active with that mod and any dependencies (first error will appear)
Click on the Starting Items button in the main menu to initiate the GUI (softlock and second error message)

**Comment by KingTate** [comment]
same issue

**Comment by VTrista** [comment]
I'm a close this issue due to the fact that the mod got updated to be compatible with the aniversary update and its patch.

Thank you very much, mod developer.
